### ISSUE TITLE
This is an issue with a task list

### ISSUE THREAD

**Issue by sinukaarel** [sinukaarel/training-gh-actions#5]
- [x] Push my commits to GitHub
- [x] Finish my changes
- [x] Open a pull request
